# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f1baa094eb3a07b60c18ca9ec76e491b3bc38aefdbc0191a6f69d4cbc4afdf05df936592f325432f23991329dfa98fd426bb90c626c84955be96f6b26bd57fe

test:
  secret_key_base: a10791fc5538ca1746784755c34edc833aabef4ddf44d3d08f0a539f5f2d195109d94966099b74214b55dc7134380ad0b4dc3216cc242c47ca61a340182e86d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
